### ISSUE TITLE
ShapeCard Shape Display Incorrect

### ISSUE THREAD

**Issue by williamzhu17** [TryShape/tryshape#104]
The ShapeCards on the Browse Now page displays the Shape incorrectly when named a certain word. In this case, the shape's name is "triangle" and has a clip-path that creates a circle. However, the ShapeCard displays a triangle instead of a circle. 

**To Reproduce**
1. Go to create a new shape. 
2. Name it "triangle"
3. Put a CSS clip-path that does not create a triangle
4. Create the shape
5. The display of the shape on the card becomes a triangle instead of a circle. 

**Expected behavior**
The correct shape is displayed on the shape card. 

Shape Data: 
![image](https://user-images.githubusercontent.com/77871333/128971227-1f274ce3-8b75-4fe9-8e38-3aa635cbefb0.png)

Display of the ShapeCard: 
![image](https://user-images.githubusercontent.com/77871333/128971263-b6ccbc40-5303-4aef-b4e1-0b74f8c34c0a.png)

**Comment by atapas** [comment]
@williamzhu17, would you take up this one to fix it?

**Comment by williamzhu17** [comment]
> @williamzhu17, would you take up this one to fix it?

Sure I can take it up.
