### ISSUE TITLE
Typo on the landing page

### ISSUE THREAD

**Issue by abhishek-munda** [TryShape/tryshape#114]
Hello. There are typos on the landing page under 'Key Features' - 'Share'. The word '_fabulously_' is misspelled as '_fabously_' and _'creativity'_ is misspelled as _'ceativity'._
The typos are in the Landing.js line 565 and 566.

![typos](https://user-images.githubusercontent.com/88289387/193357178-bc235098-6d59-48ee-89ae-9ff853543296.png)

**Comment by Chirag8023** [comment]
assign it to me

**Comment by Chirag8023** [comment]
pull request done
