### ISSUE TITLE
Website fails to load

### ISSUE THREAD

**Issue by MatijaNovosel** [TryShape/tryshape#121]
The website is stuck in an infinite loading state. The request (`https://tryshape.vercel.app/api/GET/shapes?type=public`) that gets the shapes returns a `504` status code and is not handled properly.

Additionally, there seems to be no lazy loading or pagination of any sort so the page will always make huge requests.

**Comment by CAG07** [comment]
I'm getting a `200` response code for `https://tryshape.vercel.app/app` and `https://tryshape.vercel.app/api/GET/shapes?type=public`, but it's stuck here and doesn't generate shapes 

![image](https://user-images.githubusercontent.com/18625460/194712322-6a9bd357-b54d-450a-aa37-3ac9b1db0def.png)

**Comment by Shomy032** [comment]
![image](https://user-images.githubusercontent.com/79797151/194722950-2f874eaa-d436-4812-9b95-d277f20d7a62.png)

me too

**Comment by atapas** [comment]
It was all working.. Let me check

**Comment by atapas** [comment]
Can someone debug this one to check where it is failing? I can assist.

**Comment by atapas** [comment]
> ![image](https://user-images.githubusercontent.com/79797151/194722950-2f874eaa-d436-4812-9b95-d277f20d7a62.png)
> 
> me too
> 
> Its some firebase problem, I am getting 500 error response

No not firebase because for listing the shapes, we do not interact with firebase.. We make calls to HarperDB and get the shapes. I see HarperDB is working well. We need to check at the API level.

**Comment by atapas** [comment]
> > ![image](https://user-images.githubusercontent.com/79797151/194722950-2f874eaa-d436-4812-9b95-d277f20d7a62.png)
> > me too
> > Its some firebase problem, I am getting 500 error response
> 
> No not firebase because for listing the shapes, we do not interact with firebase.. We make calls to HarperDB and get the shapes. I see HarperDB is working well. We need to check at the API level.

Seems someone tries hacking and made lots of garbage entries to the db. Now the site is back to normal... But it's sad to see someone trying to make this side project bad.

**Comment by MatijaNovosel** [comment]
> > > ![image](https://user-images.githubusercontent.com/79797151/194722950-2f874eaa-d436-4812-9b95-d277f20d7a62.png)
> > > me too
> > > Its some firebase problem, I am getting 500 error response
> > 
> > 
> > No not firebase because for listing the shapes, we do not interact with firebase.. We make calls to HarperDB and get the shapes. I see HarperDB is working well. We need to check at the API level.
> 
> Seems someone tries hacking and made lots of garbage entries to the db. Now the site is back to normal... But it's sad to see someone trying to make this side project bad.

Very sad to hear. Thank you for bringing the website online again.
