### ISSUE TITLE
fix: remove console logs on the home page

### ISSUE THREAD

**Issue by ShaneMaglangit** [TryShape/tryshape#123]
**Describe the bug**
The console prints an empty array and the number 121 when the home page is loaded

**To Reproduce**

1. Open dev tools
2. Load home page

**Expected behavior**

Keep these logs on dev environment only.

**Screenshots**

![image](https://user-images.githubusercontent.com/53674742/194751885-cce6a2ce-6006-46c5-844a-fb6ad2b42fad.png)

**Comment by hargun0360** [comment]
I would like to take this up. Could you please assign it to me?

**Comment by atapas** [comment]
Please do not remove the error logs.

**Comment by hargun0360** [comment]
okay sir

**Comment by lizardkingLK** [comment]
@atapas can you please tell me where can I get my env variables?

**Comment by ShaneMaglangit** [comment]
> @atapas can you please tell me where can I get my env variables?

Perhaps look at the README.md file. Then browse around Google search on how to get the keys for each respective external services.

**Comment by lizardkingLK** [comment]
> > @atapas can you please tell me where can I get my env variables?
> 
> Perhaps look at the README.md file. Then browse around Google search on how to get the keys for each respective external services.

sure. Thanks, I'll check. why do we need two databases? firebase and `YOUR_HARPER_DB_DATABASE_URL`?

**Comment by ShaneMaglangit** [comment]
Closed due to inactivity
