### ISSUE TITLE
Add greetings workflow and a pr template in this project

### ISSUE THREAD

**Issue by hasnainmakada-99** [TryShape/tryshape#124]
**Is your feature request related to a problem? Please describe.**

I would like to add a new greetings workflow and also a pr template to so that new contributors can clearly tell about what the pr is and they should be greeted when creating a new issue or pr

 I Would like to contribute to this issue as a part of hacktoberfest

@atapas Sir will you please assign it to me  

**Describe the solution you'd like**
Would like to integrate a new action and pr template 

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by hargun0360** [comment]
I would like to take this up. Could you please assign it to me?
