### ISSUE TITLE
Infinite Scroll Feature

### ISSUE THREAD

**Issue by Shomy032** [TryShape/tryshape#128]
# **Is your feature request related to a problem? Please describe.**

Currently, on the main page ( all public shapes ) app pulls all shapes from API, I don't think it's a scalable long-term solution, 

Now performance is ok and API is not overloaded, but what if we have a thousand shapes or 100 thousand or even a million,

# **Describe the solution you'd like**

I like to implement some kind of pagination, or even better  "infinity scroll", that way app will pull only the first few shapes and continue to pull more if needed.

For example, the first 10-20 shapes, and when the user reaches the bottom of the  page and then pulls the next 10-20,
We also need some unique default sort ( for example createdAtDate because every shape has a unique createdAtDate )
That parameter will be used as 'cursor', for infinity scroll to work

# **Describe alternatives you've considered**

I think that this feature is needed because it is a scalable, long-term solution for handling even millions of records.

Also, 99% of users will only look for the first few shapes anyway, and if they want to see more they just need to keep scrolling.

**Comment by hargun0360** [comment]
I would like to take this up. Could you please assign it to me?

**Comment by atapas** [comment]
Duplicate to #126
