### ISSUE TITLE
bug: Clip-path without spaces do not render DraggableVertices

### ISSUE THREAD

**Issue by williamzhu17** [TryShape/tryshape#58]
When typing out a clip-path in the ShapeForm, new DraggableVertices will not be created if there is no spaces in between numbers and commas. 

Type out clip-path in the shape form without spaces. The DraggableVertices will not update accordingly. 

The vertices on the preview should update even if there is no spaces.

**Comment by atapas** [comment]
@all-contributors please add @jakebolam for infrastructure, tests and code

**Comment by atapas** [comment]
@all-contributors please add @atapas for infrastructure, tests and code

**Comment by atapas** [comment]
@all-contributors please add @jakebolam for infrastructure, tests

**Comment by atapas** [comment]
@all-contributors please add @atapas  for infrastructure, tests
