### ISSUE TITLE
Trending shapes section @ landing page

### ISSUE THREAD

**Issue by nirmalkc** [TryShape/tryshape#84]
**Is your feature request related to a problem? Please describe.**
User doesn't the shapes that are currently trending

**Describe the solution you'd like**
- Keeping the user informed about the shapes that are currently most liked and re-edited quite often.
- each of the trending shape should have the owner info and when it was created will motivate the owners to come up with more trending shapes

**Comment by atapas** [comment]
@all-contributors please add @nirmalkc  for design

**Comment by atapas** [comment]
@all-contributors please add @atapas  for blog ideas mentoring platform projectManagement
