### ISSUE TITLE
Search a Shape - Entering something results in unexpected error

### ISSUE THREAD

**Issue by ckuthyar** [TryShape/tryshape#86]
*When I was trying to enter a keyword in "Search a Shape",  I was getting an unexpected error.
![TryShape_SearchAShape](https://user-images.githubusercontent.com/7517545/125151531-7886a000-e164-11eb-97c4-c24a5724a81b.png)

**Comment by atapas** [comment]
A fix has been provided for this issue. Please find the details in PR # 87.

Once the PR is tested, approved, I shall merge the fix.

**Comment by atapas** [comment]
@all-contributors please add @ckuthyar  for bug
